### ISSUE TITLE
Warning: file_put_contents(wp-content/themes/aa/aa.css): failed to open stream: Permission denied ... line 1894

### ISSUE THREAD

**Issue by jesserosenfield** [leafo/lessphp#177]
I get this error and am on Media Temple hosting. I spent some time on the phone with them and they made some modifications to the "vhosts" file to try and allow fopen, but the issue remains unresolved. Any advice on dealing with this?

Thanks!!!

**Comment by samface** [comment]
This is simply bad coding practice. If you need to write anything on the webserver's file system, there is an uploads folder for that. To enable file writing in the themes or plugins folders in a production environment is a security malpractice that no plugin or theme should ever require. Please fix this.
