### ISSUE TITLE
Inline variable does not overwrite @import variable

### ISSUE THREAD

**Issue by zsinryu** [leafo/lessphp#302]
file "variable.less"
@bodyBg: green;

file "import.less"

@import 'variable.less';

@bodyBg: red;

body { 
    line-height: 10em;
    background: @bodyBg;
}

result:
expected: @bodyBg should be red
actual:  @bodyBg is green

Regards

**Comment by tzi** [comment]
This could be closed.
It was fixed with the PR #548, available in the `v0.5.0` release.
