### ISSUE TITLE
Selector interpolation not working

### ISSUE THREAD

**Issue by mtorromeo** [leafo/lessphp#356]
Hi,
I am having this issue

```
@name: blocked;
.@{name} {
    color: black;
}
```

This test rules work correctly with lessc but not with lessphp.
The example is taken directly from lesscss documentation under the section "Selector interpolation"

Thanks

**Comment by c3k** [comment]
look at  lessphp/tests/outputs/interpolation.css (10"yeah", #"yeah"), does the selector name are deliberately quoted???

can't find a way to use them in this way

**Comment by c3k** [comment]
https://github.com/leafo/lessphp/issues/600
