### ISSUE TITLE
Invalid variable compiled when nesting more @imports

### ISSUE THREAD

**Issue by lemmon** [leafo/lessphp#431]
Let's say I have three different files nested by @import. First `master.less` is simple:

```less
@import 'variables.less';

.product {
    width:@productWidth;
}
```

...`variables.less` file:

```less
@import 'variables.base.less';

@productWidth: 200px;
```

...and finally `variables.base.less` file:

```less
@productWidth: 9999px;
```

Correctly, less css should return `width: 200px;` but lessphp is returning `9999px` instead; This worked perfectly in version `0.3.4-2` which I am still stuck at. Newest versions are useless to me since this nested imports are crucial to me.

I have tested the problem with Less mac app and less.js and everything returns 200px;

Thanks.

**Comment by tzi** [comment]
This is a duplicate ticket.
It should be fixed with the PR #433.
