### ISSUE TITLE
exception 'Exception' with message '.pull-right is undefined

### ISSUE THREAD

**Issue by krnlde** [leafo/lessphp#483]
I recently got an error when downloading the latest Bootstrap 3 revision (f9dd7466cf) from github. It now says Internal Server Error: exception 'Exception' with message '.pull-right is undefined: line: 120' in C:\xampp\htdocs\lib\vendor\Lessphp\lessc.inc.php:3465

When I investigated the exception and came to the LESS source I found out that it has problems with the following mixin (https://github.com/twbs/bootstrap/blob/master/less/dropdowns.less#L152):

```
// Right aligned dropdowns
.pull-right > .dropdown-menu {
  right: 0;
  left: auto;
}
```

This mixin will be called in the following line (https://github.com/twbs/bootstrap/blob/master/less/dropdowns.less#L188) and then crashes:

```
@media (min-width: @grid-float-breakpoint) {
  .navbar-right {
    .dropdown-menu {
      .pull-right > .dropdown-menu();
    }
  }
}
```

Commenting out the mixin call (line 188) removes the error. But I have no solution for the exception. To me the LESS statements look fine. It must've something to do with Lessphp's `peek()` method.

Any suggestions?

**Comment by snapjay** [comment]
yes - thanks @omniphx  adding  "utilities.less" worked for me

**Comment by CharlotteBao** [comment]
@omniphx thanks, work for me
