### ISSUE TITLE
Using less in php

### ISSUE THREAD

**Issue by paladox** [leafo/lessphp#597]
Hi how could I use less but alow to use a setting for example $wgLogo to choose a logo and do something like $wgLogo = array('image/to/path.svg', 'image/to/path.png');

because this is for mediawiki and at the moment I doint know how to do it so I could use less in php

Here is where it is set to allow logo to be used. https://git.wikimedia.org/blob/mediawiki%2Fcore.git/a7192f0978038b4d7ce9bd51e29f97077b407433/includes%2Fresourceloader%2FResourceLoaderSkinModule.php

**Comment by Krinkle** [comment]
To expose information from PHP to LESS, the "variables" feature can be used.
