### ISSUE TITLE
Support using less code in php

### ISSUE THREAD

**Issue by paladox** [leafo/lessphp#599]
Hi please add support for using less in php since you can only create a less file you carnt use any code in php like you can with css.

**Comment by dleffler** [comment]
You'll probably have to explain what you're actually trying to achieve...the output of the lessphp parser is 'text' within your php script which you can output to a file, or do with as you please.

**Comment by paladox** [comment]
I mean you can do css in php file but I am not sure how to use php. I use mediawiki.
