### ISSUE TITLE
Doesn't import PHP as CSS file

### ISSUE THREAD

**Issue by moniarde** [leafo/lessphp#602]
I have a PHP file generating a a whole raft of CSS classes, and am using an @import statement to include those classes for use in a LESS file. I've set the MIME type on the PHP file to output as CSS, and so there are no issues importing the PHP file into the LESS file. However, when compiling the LESS file, the PHP file is read internally, rather than as its output - that is, LessPHP attempts to compile the code of the PHP file as CSS, rather than the output of the PHP file.

(Note: I'm using this through a plugin for MODx, [LessCSS](http://modx.com/extras/package/lesscss) )

I've tracked the problem down to Parser.php:561

```
if( $file_path ){
      $this->input = file_get_contents( $file_path );
}
```

By simply 'getting' the contents of the php file, the code of the file is being parsed as CSS, rather than the output of the file. The solution below is working for me currently:

```
if( $file_path ){
    if (strpos($file_path,'.php')) {
        ob_start();
        include $file_path;
        $result = ob_get_clean();
        $this->input = $result;
    } else {
        $this->input = file_get_contents( $file_path );
    }
}
```

This will determine if the file to be processed is a php (I'm sure there's a better way of determining this than a strpos, I just didn't have time to pursue further), force the output of the file, and then forward the output for compiling.

I'm sure there's probably a better way of adding this correction, please enhance or update as necessary.

UPDATE:
Above solution doesn't deal with a query string on the call to the PHP file, so I tracked down where the query string was removed from the file name and made an ad hoc adjustment to capture the query string:
**Edit to Import.PHP:103**

```
public function getPath(){
    if ($this->path instanceof Less_Tree_Quoted) {
        $path = $this->path->value;
        $path = ( isset($this->css) || preg_match('/(\.[a-z]*$)|([\?;].*)$/',$path)) ? $path : $path . '.less';
    } else if ($this->path instanceof Less_Tree_URL) {
        $path = $this->path->value->value;
    }else{
        return null;
    }

    //edit - extract query string for later use
    preg_match('/\?(.+)/',$path,$matches);
    parse_str($matches[1],$_GET);

    //remove query string and fragment
    return preg_replace('/[\?#][^\?]*$/','',$path);
}
```

Again, I'm sure there's a better, more secure way of doing this, I'm just not focused on that at this point.

**Comment by dleffler** [comment]
I'm just an outsider who has used lessphp in the past (I moved to use less.php once I started needing Twitter Bootstrap v3), but shouldn't you be parsing your 'less php' code OUTSIDE of lessphp and then deal with it by sending the text string to the lessphp parser instead of trying to do a 'hack' inside of the lessphp parser?

Have you tried using php created 'less variables' and passing them to the lessphp parser for your .less file instead of using using a php script to generate a .less file?

**Comment by Krinkle** [comment]
Thanks for using lessphp.

This project accepts CSS and LESS syntax as either string or file path. Other formats or programs should be executed or converted before using lessphp.

If you wish to insecurely execute PHP code, that is fine. But I recommend doing that in a separate script inside your project, and then invoke lessphp on the result. It does not require additional code inside this project.
