### ISSUE TITLE
Fatal error - Can this happen?

### ISSUE THREAD

**Issue by dlaberge** [leafo/lessphp#608]
Got the following explicit error : 
# Fatal Error:

can this happen?

from the following css file :  http://jsfiddle.net/1nt86w18/

**Comment by Krinkle** [comment]
I've copied the CSS from there and ran it against leafo/lessphp with the default options on PHP 7.1, and it did not produce a fatal error.

I'm closing this old report for now, but please do report a new issue if you find a problem still.
