### ISSUE TITLE
Add Release in github

### ISSUE THREAD

**Issue by jewome62** [leafo/lessphp#615]
Hi !

You can mark release in Github with a tag.
When you make this, Github generate a zip archive. and composer can retrieve directly this archive.
But when there are no release in Github, composer must clone the repository. (x100-500 more time)

Can you publish some release in https://github.com/leafo/lessphp/tags
Ans click on "Add release notes" ans save the release

Thanks

**Comment by stof** [comment]
All releases are tagged on github. There is no need to create a release for the zip to be available (github actually allows to get the archive for any commit)

**Comment by Krinkle** [comment]
As @stof mentions, the zip files are already available from https://github.com/leafo/lessphp/tags.

Also note that Composer does not the clone the entire repository normally. If you use a version tag in your `composer.json` file, it should download the release archive only.

Perhaps you have `--prefer-source` accidentally enabled? See also <https://getcomposer.org/doc/03-cli.md#install-i>
