### ISSUE TITLE
Cannot declare class lessc, because the name is already in use

### ISSUE THREAD

**Issue by gerardreches** [leafo/lessphp#623]
Hi, I'm getting this error on a Laravel project (with lessphp installed via composer) when I try to require the package in a .php file:

> FatalErrorException in lessc.inc.php line 40: Cannot declare class lessc, because the name is already in use

Another thing is that `require "lessc.inc.php"` gives me an error:

> Failed opening required 'lessc.inc.php' 

So I need to require the full path to the file, and then I get the first error.

I'm not sure if it's a laravel problem or a package problem, so I'm not sure if I am asking in the right place.

**Comment by gerardreches** [comment]
I didn't need a `require`, composer already takes care of it. Little misunderstanding.

**Comment by ppshobi** [comment]
in case if you need it, consider using require_once() instead of require
